export ZSH=$HOME/.oh-my-zsh

###### HOMEBREW
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# Prevent Homebrew from reporting - https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Analytics.md
export HOMEBREW_NO_ANALYTICS=1

###### OH-MY-ZSH
# You can change the theme with another one: https://github.com/robbyrussell/oh-my-zsh/wiki/themes
ZSH_THEME="robbyrussell"

# Useful plugins for Rails development. Syntax Highlighting is always last
plugins=(git gitfast last-working-dir common-aliases history-substring-search osx rbenv ruby zsh-syntax-highlighting)

# Disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Actually load Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

###### RUBY + RAILS
# Add ruby version on prompt (float right)
if [ -x "$(command -v rbenv)" ]; then RPS1='[$(ruby_prompt_info)]$EPS1'; fi

# Rails and Ruby uses the local `bin` folder to store binstubs.
# So instead of running `bin/rails` like the doc says, just run `rails`
# Same for `./node_modules/.bin` and nodejs
export PATH="./bin:./node_modules/.bin:${PATH}:/usr/local/sbin"

# Paths used to run gem commands from command line, e.g. RSPEC
# export PATH=/usr/local/opt/ruby/bin:$PATH
# export PATH=/usr/local/lib/ruby/gems/2.5.0/bin:$PATH

# Load rbenv if installed (To manage Ruby versions)
export PATH="${HOME}/.rbenv/bin:${PATH}" # Needed for Linux/WSL
type -a rbenv > /dev/null && eval "$(rbenv init -)"

###### PYTHON
# Load pyenv (To manage Python versions)
# export PATH="${HOME}/.pyenv/bin:${PATH}" # Needed for Linux/WSL
# type -a pyenv > /dev/null && eval "$(pyenv init -)" # && eval "$(pyenv virtualenv-init -)"

###### MISCELLANEOUS
# Store your own aliases in the ~/.aliases file and load them here.
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Encoding stuff for the terminal
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true
